title: CORGi @ CMU
logo: images/arya.png
description: Computer Organization Research Group led by Prof. Nathan Beckmann

theme: jekyll-theme-minimal

collections:
    people:
        output: true
    funding:
    projects:
    publications:

defaults:
    - scope:
        path: ""
        type: "people"
      values:
        layout: "people"
    - scope:
        path: ""
      values:
        layout: "default"
