title: CORGi
description: Computer Organization Research Group @CMU led by Prof. Nathan Beckmann

theme: jekyll-theme-minimal

collections:
    - people
    - funding
    - projects
    - publications
