title: CORGi @ CMU
logo: images/arya.png
description: Computer Organization Research Group led by Prof. Nathan Beckmann

theme: jekyll-theme-minimal
#remote_theme: page-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme

collections:
    people:
        output: true
    funding:
        output: true
    projects:
        output: true

defaults:
    - scope:
        path: ""
        type: "people"
      values:
        layout: "people"
    - scope:
        path: ""
        type: "projects"
      values:
        layout: "projects"
    - scope:
        path: ""
        type: "funding"
      values:
        layout: "funding"
    - scope:
        path: ""
      values:
        layout: "default"
