title: CORGi @ CMU
logo: images/arya.png
description: Computer Organization Research Group led by Prof. Nathan Beckmann

theme: jekyll-theme-minimal

collections:
    - people
    - funding
    - projects
    - publications
